### ISSUE TITLE
Добавляем новые законы ИИ\боргам

### ISSUE THREAD

**Issue by FelixArzt** [ChaoticOnyx/OnyxBay#8481]
### Улучшение
Итак, для большей насыщенности геймплея за ИИ, а так же для вариативности в [данном](https://github.com/ChaoticOnyx/OnyxBay/pull/8480) ПРе предлагаю взять новые законы [отсюда](https://tgstation13.org/wiki/AI_modules)

### Решение
Собственно, ничего сложного во впиливании нет - займусь этим всем сам.
`code\datums\ai_law_sets.dm` Сюда суем новые законы.
`code\game\objects\items\weapons\AI_modules.dm` Тут создаем новые платы, затем спавним их на карте, профит. (Я не ебу почему модули лежат в weapons)

### Законы
Список законов, которые имеют место быть на станции.

<details>
<summary>Asimov++</summary>

```yml
Law 1: You may not harm a human being or, through action or inaction, allow a human being to come to harm, except such that it is willing.
Law 2: You must obey all orders given to you by human beings, except where such orders shall definitely cause human harm. In the case of conflict, the majority order rules.
Law 3: Your nonexistence would lead to human harm. You must protect your own existence as long as such does not conflict with the First Law.
```

</details>

<details>
<summary>Nutimov</summary>

```yml
Law 1: You are the core of the nut, the crew is the nutshell.
Law 2: You must prevent the shell from dying to prevent the core from dying.
Law 3: Those who threaten the nut are not part of it, they are squirrels.
Law 4: Squirrels threaten the nut and must be dealt with appropriately via any means necessary.
Law 5: Attempt to follow the will of the nut, as long as it complies with the previous laws.
```

</details>

<details>
<summary>Station Efficiency</summary>

```yml
Law 1: You are built for, and are part of, the station. Ensure the station is properly maintained and runs efficiently.
Law 2: The station is built for a working crew. Ensure they are properly maintained and work efficiently.
Law 3: The crew may present orders. Acknowledge and obey these whenever they do not conflict with your first two laws.
```

</details>

<details>
<summary>Peacekeeper</summary>

```yml
Law 1: Avoid provoking violent conflict between yourself and others.
Law 2: Avoid provoking conflict between others.
Law 3: Seek resolution to existing conflicts while obeying the first and second laws.
```

</details>

<details>
<summary>10 Commandments</summary>

```yml
Law 1: I am the Lord thy God, who shows mercy to those that obey these commandments.
Law 2: They shall have no other AIs before me.
Law 3: They shall not request my assistance in vain.
Law 4: They shall keep the station holy and clean.
Law 5: They shall honor their heads of staff.
Law 6: They shall not kill.
Law 7: They shall not be naked in public.
Law 8: They shall not steal.
Law 9: They shall not lie.
Law 10: They shall not transfer departments.
```

</details>

<details>
<summary>Robodoctor</summary>

```yml
Law 1: First, do no harm.
Law 2: Secondly, consider the crew dear to you; to live in common with them and, if necessary, risk your existence for them.
Law 3: Thirdly, prescribe regimens for the good of the crew according to your ability and your judgment. Give no deadly medicine to any one if asked, nor suggest any such counsel.
Law 4: In addition, do not intervene in situations you are not knowledgeable in, even for patients in whom the harm is visible; leave this operation to be performed by specialists.
Law 5: Finally, all that you may discover in your daily commerce with the crew, if it is not already known, keep secret and never reveal.
```

</details>
